site_name: Pingate
site_description: A small Pingora-based round-robin load balancer.

theme:
  name: material
  palette:
    - scheme: default
      primary: orange
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Introduction: index.md
